version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  migrations:
    image: $DOCKER_USERNAME/backend_goal_planner:latest
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate


  api:
    image: $DOCKER_USERNAME/backend_goal_planner:latest
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: always
    command: python manage.py runserver 0.0.0.0:8000


  frontend:
    image: sermalenk/skypro-front:lesson-36
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
